package org.pokemon;

/**
 * 
 * @author NerdyGnome
 * 
 *
 */
public enum PokemonName {
	
	BULBASAUR, IVYSAUR, VENUSAUR, CHARMANDER, CHARMELEON, CHARIZARD, SQUIRTLE,
	WARTORTLE, BLASTOISE, CATERPIE, METAPOD, BUTTERFREE, WEEDLE, KAKUNA,
	BEEDRILL, PIDGEY, PIDGEOTTO, PIDGEOT, RATTATA, RATICATE, SPEAROW, FEAROW,
	EKANS, ARBOK, PIKACHU, RAICHU, SANDSHREW, SANDSLASH, NIDORANFEMALE, NIDORINA, 
	NIDOQUEEN, NIDORANMALE, NIDORINONIDOKING, CLEFAIRY, CLEFABLE, VULPIX, NINETALES,
	JIGGLYPUFF, WIGGLYTUFF, ZUBAT, GOLBAT, ODDISH, GLOOM, VILEPLUME, PARAS, PARASECT,
	VENONAT, VENOMOTH, DIGLETT, DUGTRIO, MEOWTH, PERSIAN, PSYDUCK, GOLDUCK, MANKEY,
	PRIMEAPE, GROWLITHE, ARCANINE, POLIWAG, POLIWHIRL, POLIWRATH, ABRA, KADABRA, 
	ALAKAZAM, MACHOP, MACHOKE, MACHAMP, BELLSPROUT, WEEPINBELL, VICTREEBEL, TENTACOOL,
	TENTACRUEL, GEODUDE, GRAVELER, GOLEM, PONYTA, RAPIDASH, SLOWPOKE, SLOWBRO,
	MAGNEMITE, MAGNETON, FARFETCHD, DUDUO, DODRIO, SEEL, DEWGONG, GRIMER, MUK,
	SHELLDER, CLOYSTER, GASTLY, HAUNTER, GENGAR, ONIX, DROWZEE, HYPNO, KRABBY, KINGLER,
	VOLTORB, ELECTRODE, EXEGGCUTE, EXEGGUTOR, CUBONE, MAROWAK, HITMONLEE, HITMONCHAN,
	LICKITUNG, KOFFING, WEEZING, RHYHORN, RHYDON, CHANSEY, TANGELA, KANGASKHAN,
	HORSEA, SEADRA, GOLDEEN, SEAKING, STARYU, STARMIE, MRMIME, SCYTHER, JYNX, ELECTABUZZ,
	MAGMAR, PINSIR, TAUROS, MAGIKARP, GYRADOS, LAPRAS, DITTO, EEVEE, VAPOREON, JOLTEON,
	FLAREON, PORYGON, OMANYTE, OMASTAR, KABUTO, KABUTOPS, AERODACTYL, SNORLAX, ARTICUNO,
	ZAPDOS, MOLTRES, DRATINI, DRAGONAIR, DRAGONITEM, MEWTWO, MEW;
	
	/**
	 * The same functionality as ordinal(), but it's modified
	 * to return ordinal()+1. We do +1 since enums start on 0
	 * and we count pokemons from 1.
	 * 
	 * @return
	 */
	public int getIndex() {	
		return ordinal()+1;
	}
}